name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Verify
    runs-on: macos-26
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      # Build the project
      - name: Build
        run: |
          xcodebuild build \
            -project Interviews.xcodeproj \
            -scheme Interviews \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      # Run unit tests
      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project Interviews.xcodeproj \
            -scheme Interviews \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -testPlan Interviews \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
  automerge:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Check dependabot
        id: check_author
        run: |
          if [[ "${{ github.actor }}" == *dependabot* ]]; then
            echo "is_dependabot=true" >> $GITHUB_ENV
          else
            echo "is_dependabot=false" >> $GITHUB_ENV
          fi
      - name: metadata
        if: env.is_dependabot == 'true'
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: merge_patch
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' && env.is_dependabot == 'true'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: merge_minor
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' && env.is_dependabot == 'true'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  update_release_draft:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
